baseURL = "http://example.org/"
languageCode = "en-us"
title = "andy whale"
theme = "mediumish"
copyright = "Andy Whale 2019"

[params]
  description ="posts about something & nothing"

[params.author]
  name = "Andy Whale"
  thumbnail = "images/glasses-icon.png"
  description = "Development lead at Numiko, Game Dev enthusiast."

[params.index]
  picture = "images/glasses-icon.png"
  title = "andy whale"
  subtitle = "Development lead at Numiko (Symfony, PHP, Python, Javascript, Drupal), Game Dev enthusiast (Unity, C#), problem solver, questioner of things, keen photographer, struggling guitarist, juggler, dad ..."
  mdtext = '''
### web developer
By day I write websites for Numiko where we endeavour to work for clients
inspiring social good; built mostly using the PHP stack.
<div class="">
  <a class="badge badge-success badge-pill badge-large" href="/tags/numiko/">numiko</a>
  <a class="badge badge-success badge-pill badge-large" href="/tags/drupalmodule/">drupalmodule</a>
</div>
'''
  mdtext2 = '''
### aspiring game developer
By night I build games in Unity and C# and then bin them 4 - 6 weeks
later due to the ideas becoming either unplayable or ludicrously complex.
<div class="">
  <a class="badge badge-success badge-pill badge-large" href="/tags/gamedev/">gamedev</a>
</div>
'''
  mdtext3 = '''
### published photographer
I shoot a Nikon D600 and love to take time out to take photos, but it really is just a hobby. Although one of my viking shots has been used in a book ;-)
'''
  alertbar = false

[params.social]
  github = "andywhale"
  linkedin = "andywhale"
  twitter = "andywhalephoto"
  instagram = "andywhalephoto"
  drupal = "andy_w"
  flickr = "awhale"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"